
// This file has been generated by the GUI designer. Do not modify.
namespace ToyLanguage
{
	public partial class MainWindow
	{
		private global::Gtk.VBox MainVBox;
		
		private global::Gtk.Label WelcomeLbl;
		
		private global::Gtk.Button InsertBtn;
		
		private global::Gtk.Button OneStep;
		
		private global::Gtk.Button FullStepBtn;
		
		private global::Gtk.Button SerializeBtn;
		
		private global::Gtk.Button DeserializeBtn;
		
		private global::Gtk.CheckButton LogCheck;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ToyLanguage.MainWindow
			this.Name = "ToyLanguage.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ToyLanguage.MainWindow.Gtk.Container+ContainerChild
			this.MainVBox = new global::Gtk.VBox ();
			this.MainVBox.Name = "MainVBox";
			this.MainVBox.Spacing = 6;
			this.MainVBox.BorderWidth = ((uint)(6));
			// Container child MainVBox.Gtk.Box+BoxChild
			this.WelcomeLbl = new global::Gtk.Label ();
			this.WelcomeLbl.Name = "WelcomeLbl";
			this.WelcomeLbl.LabelProp = global::Mono.Unix.Catalog.GetString ("Welcome to ToyLanguage! Choose one of the options below.");
			this.MainVBox.Add (this.WelcomeLbl);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.WelcomeLbl]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.InsertBtn = new global::Gtk.Button ();
			this.InsertBtn.CanFocus = true;
			this.InsertBtn.Name = "InsertBtn";
			this.InsertBtn.UseUnderline = true;
			this.InsertBtn.Label = global::Mono.Unix.Catalog.GetString ("Insert a program");
			this.MainVBox.Add (this.InsertBtn);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.InsertBtn]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.OneStep = new global::Gtk.Button ();
			this.OneStep.CanFocus = true;
			this.OneStep.Name = "OneStep";
			this.OneStep.UseUnderline = true;
			this.OneStep.Label = global::Mono.Unix.Catalog.GetString ("OneStep");
			this.MainVBox.Add (this.OneStep);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.OneStep]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.FullStepBtn = new global::Gtk.Button ();
			this.FullStepBtn.CanFocus = true;
			this.FullStepBtn.Name = "FullStepBtn";
			this.FullStepBtn.UseUnderline = true;
			this.FullStepBtn.Label = global::Mono.Unix.Catalog.GetString ("Full Step");
			this.MainVBox.Add (this.FullStepBtn);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.FullStepBtn]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.SerializeBtn = new global::Gtk.Button ();
			this.SerializeBtn.CanFocus = true;
			this.SerializeBtn.Name = "SerializeBtn";
			this.SerializeBtn.UseUnderline = true;
			this.SerializeBtn.Label = global::Mono.Unix.Catalog.GetString ("Serialize");
			this.MainVBox.Add (this.SerializeBtn);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.SerializeBtn]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.DeserializeBtn = new global::Gtk.Button ();
			this.DeserializeBtn.CanFocus = true;
			this.DeserializeBtn.Name = "DeserializeBtn";
			this.DeserializeBtn.UseUnderline = true;
			this.DeserializeBtn.Label = global::Mono.Unix.Catalog.GetString ("Deserialize");
			this.MainVBox.Add (this.DeserializeBtn);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.DeserializeBtn]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.LogCheck = new global::Gtk.CheckButton ();
			this.LogCheck.CanFocus = true;
			this.LogCheck.Name = "LogCheck";
			this.LogCheck.Label = global::Mono.Unix.Catalog.GetString ("Write to file?");
			this.LogCheck.DrawIndicator = true;
			this.LogCheck.UseUnderline = true;
			this.MainVBox.Add (this.LogCheck);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.LogCheck]));
			w7.Position = 6;
			w7.Expand = false;
			w7.Fill = false;
			this.Add (this.MainVBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 414;
			this.DefaultHeight = 239;
			this.Show ();
			this.InsertBtn.Clicked += new global::System.EventHandler (this.InsertBtnClicked);
			this.OneStep.Clicked += new global::System.EventHandler (this.OneBtnClicked);
			this.FullStepBtn.Clicked += new global::System.EventHandler (this.FullBtnClicked);
			this.SerializeBtn.Clicked += new global::System.EventHandler (this.SerializeBtnClicked);
			this.DeserializeBtn.Clicked += new global::System.EventHandler (this.DeserializeBtnClick);
			this.LogCheck.Toggled += new global::System.EventHandler (this.LogCheckTouched);
		}
	}
}
