
// This file has been generated by the GUI designer. Do not modify.
namespace ToyLanguage
{
	public partial class TextDialogBox
	{
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.Label MainLabel;
		
		private global::Gtk.Entry TextEntry;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ToyLanguage.TextDialogBox
			this.Name = "ToyLanguage.TextDialogBox";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child ToyLanguage.TextDialogBox.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.MainLabel = new global::Gtk.Label ();
			this.MainLabel.Name = "MainLabel";
			this.MainLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Please input:");
			this.vbox10.Add (this.MainLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.MainLabel]));
			w2.Position = 2;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox9.Add (this.vbox10);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox10]));
			w3.Position = 0;
			// Container child vbox9.Gtk.Box+BoxChild
			this.TextEntry = new global::Gtk.Entry ();
			this.TextEntry.CanFocus = true;
			this.TextEntry.Name = "TextEntry";
			this.TextEntry.IsEditable = true;
			this.TextEntry.InvisibleChar = '•';
			this.vbox9.Add (this.TextEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.TextEntry]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w1.Add (this.vbox9);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox9]));
			w5.Position = 0;
			// Internal child ToyLanguage.TextDialogBox.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonOk]));
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 143;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.okBtnClicked);
		}
	}
}
