
// This file has been generated by the GUI designer. Do not modify.
namespace ToyLanguage
{
	public partial class ChoiceDialogBox
	{
		private global::Gtk.VBox vbox11;
		
		private global::Gtk.VBox vbox12;
		
		private global::Gtk.Label DialogLabel;
		
		private global::Gtk.ComboBox ComboBox;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ToyLanguage.ChoiceDialogBox
			this.Name = "ToyLanguage.ChoiceDialogBox";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child ToyLanguage.ChoiceDialogBox.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.DialogLabel = new global::Gtk.Label ();
			this.DialogLabel.Name = "DialogLabel";
			this.DialogLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Please Input:");
			this.vbox12.Add (this.DialogLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.DialogLabel]));
			w2.Position = 2;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox11.Add (this.vbox12);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.vbox12]));
			w3.Position = 0;
			// Container child vbox11.Gtk.Box+BoxChild
			this.ComboBox = global::Gtk.ComboBox.NewText ();
			this.ComboBox.Name = "ComboBox";
			this.vbox11.Add (this.ComboBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.ComboBox]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			w1.Add (this.vbox11);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox11]));
			w5.Position = 0;
			// Internal child ToyLanguage.ChoiceDialogBox.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "dialog1_ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.buttonOk]));
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 147;
			this.Show ();
			this.ComboBox.Changed += new global::System.EventHandler (this.ComboChangedValue);
			this.buttonOk.Clicked += new global::System.EventHandler (this.okBtnClicked);
		}
	}
}
