
// This file has been generated by the GUI designer. Do not modify.
namespace ToyLanguage
{
	public partial class ProgramInsertWindow
	{
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView prgText;
		
		private global::Gtk.Button StartBtn;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ToyLanguage.ProgramInsertWindow
			this.Name = "ToyLanguage.ProgramInsertWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ProgramInsertWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ToyLanguage.ProgramInsertWindow.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.prgText = new global::Gtk.TextView ();
			this.prgText.CanFocus = true;
			this.prgText.Name = "prgText";
			this.prgText.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.prgText);
			this.vbox8.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox8.Gtk.Box+BoxChild
			this.StartBtn = new global::Gtk.Button ();
			this.StartBtn.CanFocus = true;
			this.StartBtn.Name = "StartBtn";
			this.StartBtn.UseUnderline = true;
			this.StartBtn.Label = global::Mono.Unix.Catalog.GetString ("Start");
			this.vbox8.Add (this.StartBtn);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.StartBtn]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox8);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.StartBtn.Clicked += new global::System.EventHandler (this.StartInsertClicked);
		}
	}
}
