
// This file has been generated by the GUI designer. Do not modify.
namespace ToyLanguage
{
	public partial class OneStepWindow
	{
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView OneStepText;
		
		private global::Gtk.Button OneStepBtn;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ToyLanguage.OneStepWindow
			this.Name = "ToyLanguage.OneStepWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("OneStepWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ToyLanguage.OneStepWindow.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.OneStepText = new global::Gtk.TextView ();
			this.OneStepText.CanFocus = true;
			this.OneStepText.Name = "OneStepText";
			this.OneStepText.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.OneStepText);
			this.vbox5.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.OneStepBtn = new global::Gtk.Button ();
			this.OneStepBtn.CanFocus = true;
			this.OneStepBtn.Name = "OneStepBtn";
			this.OneStepBtn.UseUnderline = true;
			this.OneStepBtn.Label = global::Mono.Unix.Catalog.GetString ("One Step");
			this.vbox5.Add (this.OneStepBtn);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.OneStepBtn]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.vbox5);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.OneStepBtn.Clicked += new global::System.EventHandler (this.OneStepClicked);
		}
	}
}
